import { SignIn, SignInButton, SignOutButton, SignUp, SignUpButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const {data} = api.post.getAll.useQuery();

  console.log(data)

  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
          <SignUp />
          
          {!user.isSignedIn && <SignUpButton /> && <SignInButton />}
          {!!user.isSignedIn && <SignOutButton />}

          <div>
            {data?.map((post) => (<div key={post.authorId}>{post.content}</div>))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
